language: ruby
rvm:
- 2.1.1
before_install: gem update bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
env:
  global:
  - AR4_S_K_B=09ced0f5527b74049d122b000b36e7d5531584788dc2650ac0e8ade11d79668d8978ad725fe2c0dcba4f0f2cff7bba336fc726019def6b2dea969554c7deb2d8
  - secure: gr01YSiXwMpOUTWUcuR7O0hcvdE8xgYr+ugpL9H94Xvy7uN14bXF5FDYCLqsZxsXcpNA/vq8rX0RxOZcxFi+yxSbvZgSxryYzft6/fUWg/jIRrRMWSCIAjhHCUAyyTF89GsRBrn1YLeaKNAsEHvalwSyQpNakZnwQzVpsXsWcDQ=
